name: Pull Backend 

on:
  pull_request:
    branches:
      - master


jobs:
  qa_backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt install python3-pip
          cd backend
          pip install -r requirements.txt

      - name: Run tests
        run: |
          cd backend
          uvicorn main:app --reload &
          pytest -v