name: Pull Backend 

on:
  pull_request:
    branches:
      - master


jobs:
  qa_backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update  
          sudo apt install python3-pip python3-venv
          cd backend
          python3 -m venv venv
          source venv/bin/activate 
          pip install --upgrade pip setuptools wheel
          pip install -r requirements.txt
      
      - name: Create env
        run: |
          echo API_KEY=${{secrets.API_KEY}} >> ./backend/.env
      - name: Run tests
        run: |
          cd backend
          uvicorn main:app --reload &
          pytest -v