name: Deploy Backend to Amazon ECS

on:
  push:
    branches:
      - master

env:
  AWS_REGION: us-west-1
  ECS_CLUSTER: MailAppCluster
  ECS_SERVICE: MailBackendMain
  REPOSITORY: 891377268337.dkr.ecr.us-east-1.amazonaws.com


jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-1

      - name: Login to Amazon ECR Private
        uses: aws-actions/amazon-ecr-login@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Build Backend, tag, and push image to Amazon ECR
        run: |
          echo API_KEY=${{secrets.API_KEY}} >> ./backend/.env

          docker build -t medical_assistant_backend ./backend
          docker tag medical_assistant_backend:latest $REPOSITORY/medical_assistant_backend:latest
          docker push $REPOSITORY/medical_assistant_backend:latest

          
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Deploy to ECS
        run: |
          aws ecs update-service --cluster ${{ env.ECS_CLUSTER }} --service ${{ env.ECS_SERVICE }} --force-new-deployment